apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: tb-fnn-cvr-001
  name: tb-fnn-cvr-001
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tb-fnn-cvr-001
  template:
    metadata:
      labels:
        app: tb-fnn-cvr-001
    spec:
      volumes:
      - name: my-nas-pvc
        persistentVolumeClaim:
            claimName: pvc-fnn-cvr-001
      containers:
      - name: tensorboard
        image: tensorflow/tensorflow:1.7.0
        imagePullPolicy: Always
        command:
         - /usr/local/bin/tensorboard
        args:
        - --logdir
        - /data/model/fnn-cvr-001/
        volumeMounts:
        - name: my-nas-pvc
          mountPath: "/data"
        ports:
        - containerPort: 6006
          protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always