apiVersion: kubeflow.org/v1alpha1
kind: TFJob
metadata:
  name: tfjob-export-deepfm-ctr-001
spec:
  replicaSpecs:
    - replicas: 1 # 1 Master
      template:
        spec:
          containers:
            - image: tensorflow/tensorflow:1.5.0
              name: tensorflow
              command: ["python", "/data/app/deepfm-ctr-001/main.py"]
              args:
                - --task_type=export
              volumeMounts:
              - name: my-nas-pvc
                mountPath: "/data"
          volumes:
            - name: my-nas-pvc
              persistentVolumeClaim:
                claimName: pvc-deepfm-ctr-001
          restartPolicy: Never