kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-dcn-ctr-001
spec:
  storageClassName: nas
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      tfjob: tfjob-dcn-ctr-001