kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-deepfm-cvr-002
spec:
  storageClassName: nas
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      tfjob: tfjob-deepfm-cvr-002