apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-wopnn-cvr-001
  labels:
    tfjob: tfjob-wopnn-cvr-001
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nas
  flexVolume:
    driver: "alicloud/nas"
    options:
      mode: "755"
      path: /data
      server: 0802d48712-bvu30.cn-hangzhou.nas.aliyuncs.com
      vers: "4.0"
